import streamlit as st

from src.llm_backends import active_backend, detect_ollama, query_with_backend
from src.retrieval import search_corpus

DEFAULT_PORT = 8506
DEFAULT_QUESTION = "What are competitors doing in payments and fraud detection in Q1 2026?"

st.set_page_config(page_title="Market Intelligence", page_icon="📊", layout="wide")
st.title("LLM-Driven Market Intelligence")

backend = active_backend()
ollama_ok, ollama_model = detect_ollama()

with st.sidebar:
    st.header("AI backend")
    if backend == "openai":
        st.success("OpenAI + Pinecone")
    elif backend == "ollama":
        st.success(f"Ollama — `{ollama_model}`")
    else:
        st.info("Local RAG (corpus search)")
        st.markdown(
            "**Want live AI answers?** Install free open-source [Ollama](https://ollama.com), then run:\n"
            "```\nollama pull llama3.2\nollama serve\n```"
            "Restart this app — answers will be generated by the local model."
        )

    force_backend = st.selectbox(
        "Force backend",
        options=["auto", "ollama", "local"],
        format_func=lambda x: {
            "auto": "Auto (best available)",
            "ollama": "Ollama (open-source LLM)",
            "local": "Local RAG only",
        }[x],
    )

st.caption(
    "Ask about competitors, launches, or market trends. "
    "With Ollama running, responses are generated by a local open-source LLM over the demo corpus."
)

question = st.text_input("Ask a market intelligence question:", value=DEFAULT_QUESTION)

if st.button("Analyze", type="primary"):
    with st.spinner("Retrieving signals and generating insight..."):
        chosen = None if force_backend == "auto" else force_backend
        if chosen == "ollama" and not ollama_ok:
            st.error(
                "Ollama is not running. Install from https://ollama.com, run `ollama pull llama3.2`, "
                "then `ollama serve` and try again."
            )
        else:
            hits = search_corpus(question)
            with st.expander(f"Retrieved {len(hits)} corpus snippets", expanded=False):
                for h in hits:
                    st.markdown(f"- {h['text']}")
            st.markdown(query_with_backend(question, chosen))

st.divider()
st.markdown(f"**Run locally:** `streamlit run app.py` → http://localhost:{DEFAULT_PORT}")
